name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit:latest
        env:
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1
        ports:
          - 1025:1025
          - 8025:8025
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          check-latest: true
          node-version: "22"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run linters
        run: yarn lint
      - name: Run tests
        run: yarn test
        env:
          MAILPIT_HOST: mailpit
          MAILPIT_HTTP_PORT: 8025
          MAILPIT_SMTP_PORT: 1025
          MAILPIT_SMTP_USER: username
          MAILPIT_SMTP_PASS: password
          MAILPIT_SMTP_SECURE: false
